Debug 0
GenericLanguage "en"
GenericExecuteSynth "printf %s \"$DATA\" | /usr/bin/piper-tts --model /home/atharv/.piper-voices/en_GB/alan/medium/en_GB-alan-medium.onnx --output_raw | /usr/bin/pw-play --rate 22050 --channels 1 --format s16 --raw - "
AddVoice "en" "MALE1" "alan"
DefaultVoice "alan"
