Debug 0
GenericLanguage "en"
GenericExecuteSynth "printf %s \"$DATA\" | /usr/bin/piper-tts --model /home/atharv/.piper-voices/en_GB/cori/medium/en_GB-cori-medium.onnx --output_raw | /usr/bin/pw-play --rate 22050 --channels 1 --format s16 --raw - "
AddVoice "en" "FEMALE1" "cori"
DefaultVoice "cori"
