exec swayidle -w \
    timeout 300 'swaymsg "exec loginctl lock-session"' \
    timeout 600 'swaymsg "output * power off"' \
    resume 'swaymsg "output * power on"' \
    lock 'swaylock -f --config ~/.config/swaylock/current.conf' \
    before-sleep 'loginctl lock-session'

exec_always autotiling
exec_always nm-applet --indicator
exec_always blueman-applet
exec_always mako
exec_always dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec_always rm -f /tmp/waybar_inhibitor_active
exec speedcrunch

# Polkit Agent (The one we chose)
exec systemctl --user start hyprpolkitagent
