# -------------------------------------------------------------------------
# BATTERY CARE (The 50-80% Rule)
# -------------------------------------------------------------------------
START_CHARGE_THRESH_BAT0=50
STOP_CHARGE_THRESH_BAT0=80
