import os

# --- Configuration ---
output_dir = os.path.expanduser("sway_configs")

# Define the 14 accent colors requested
accents = [
    "rosewater", "flamingo", "pink", "mauve", "red", "maroon", "peach", 
    "yellow", "green", "teal", "sky", "sapphire", "blue", "lavender"
]

# Define the Palette (Hex codes for all flavors)
flavors = {
    "mocha": {
        "base": "#1e1e2e", "mantle": "#181825", "text": "#cdd6f4", "overlay0": "#6c7086",
        "rosewater": "#f5e0dc", "flamingo": "#f2cdcd", "pink": "#f5c2e7", "mauve": "#cba6f7",
        "red": "#f38ba8", "maroon": "#eba0ac", "peach": "#fab387", "yellow": "#f9e2af",
        "green": "#a6e3a1", "teal": "#94e2d5", "sky": "#89dceb", "sapphire": "#74c7ec",
        "blue": "#89b4fa", "lavender": "#b4befe"
    },
    "macchiato": {
        "base": "#24273a", "mantle": "#1e2030", "text": "#cad3f5", "overlay0": "#6e738d",
        "rosewater": "#f4dbd6", "flamingo": "#f0c6c6", "pink": "#f5bde6", "mauve": "#c6a0f6",
        "red": "#ed8796", "maroon": "#ee99a0", "peach": "#f5a97f", "yellow": "#eed49f",
        "green": "#a6da95", "teal": "#8bd5ca", "sky": "#91d7e3", "sapphire": "#7dc4e4",
        "blue": "#8aadf4", "lavender": "#b7bdf8"
    },
    "frappe": {
        "base": "#303446", "mantle": "#292c3c", "text": "#c6d0f5", "overlay0": "#737994",
        "rosewater": "#f2d5cf", "flamingo": "#eebebe", "pink": "#f4b8e4", "mauve": "#ca9ee6",
        "red": "#e78284", "maroon": "#ea999c", "peach": "#ef9f76", "yellow": "#e5c890",
        "green": "#a6d189", "teal": "#81c8be", "sky": "#99d1db", "sapphire": "#85c1dc",
        "blue": "#8caaee", "lavender": "#babbf1"
    },
    "latte": {
        "base": "#eff1f5", "mantle": "#e6e9ef", "text": "#4c4f69", "overlay0": "#9ca0b0",
        "rosewater": "#dc8a78", "flamingo": "#dd7878", "pink": "#ea76cb", "mauve": "#8839ef",
        "red": "#d20f39", "maroon": "#e64553", "peach": "#fe640b", "yellow": "#df8e1d",
        "green": "#40a02b", "teal": "#179299", "sky": "#04a5e5", "sapphire": "#209fb5",
        "blue": "#1e66f5", "lavender": "#7287fd"
    }
}

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Template for the Sway config file
template = """# Catppuccin {flavor_title} - {accent_title} Accent
# Generated by Python Script

set $base       {base}
set $mantle     {mantle}
set $text       {text}
set $overlay0   {overlay0}
set $red        {red}
set $accent     {accent_hex}

# Property Name         Border      Background  Text    Indicator   Child Border
client.focused          $accent     $accent     $base   $accent     $accent
client.focused_inactive $overlay0   $base       $text   $overlay0   $overlay0
client.unfocused        $overlay0   $base       $text   $overlay0   $overlay0
client.urgent           $red        $base       $red    $overlay0   $red
client.placeholder      $overlay0   $base       $text   $overlay0   $overlay0
client.background       $base
"""

# Generate files
print(f"Generating Sway config files in {output_dir}...")

for flavor_name, colors in flavors.items():
    for accent_name in accents:
        # Get the specific hex code for this accent in this flavor
        accent_hex = colors.get(accent_name)
        
        # Format the content
        content = template.format(
            flavor_title=flavor_name.capitalize(),
            accent_title=accent_name.capitalize(),
            base=colors["base"],
            mantle=colors["mantle"],
            text=colors["text"],
            overlay0=colors["overlay0"],
            red=colors["red"],
            accent_hex=accent_hex
        )
        
        # Define filename: catppuccin-<flavor>-<accent>.conf
        filename = f"catppuccin-{flavor_name}-{accent_name}.conf"
        filepath = os.path.join(output_dir, filename)
        
        # Write to file
        with open(filepath, "w") as f:
            f.write(content)

print(f"Success! Generated {len(flavors) * len(accents)} configuration files.")
