# ~/.config/swaylock/themes/arc-dark.conf
color=383c4a
indicator-radius=100
indicator-thickness=12
ring-color=4b5162
key-hl-color=5294e2
bs-hl-color=cc575d
text-color=afbac5
line-color=00000000
inside-color=383c4a
separator-color=00000000

# Status Colors
ring-ver-color=5294e2
inside-ver-color=383c4a
ring-wrong-color=cc575d
inside-wrong-color=383c4a
ring-clear-color=80a87f
inside-clear-color=383c4a
