# Catppuccin Macchiato Pink Optimized Swaylock Config
color=24273a
indicator-radius=100
indicator-thickness=12
ring-color=f5bde6
key-hl-color=5b6078
bs-hl-color=f38ba8
text-color=cad3f5
line-color=00000000
inside-color=24273a
separator-color=00000000

# Status Colors
ring-ver-color=f5bde6
inside-ver-color=24273a
ring-wrong-color=f38ba8
inside-wrong-color=24273a
ring-clear-color=a6e3a1
inside-clear-color=24273a
