# Catppuccin Frappe Peach Optimized Swaylock Config
color=303446
indicator-radius=100
indicator-thickness=12
ring-color=ef9f76
key-hl-color=626880
bs-hl-color=f38ba8
text-color=c6d0f5
line-color=00000000
inside-color=303446
separator-color=00000000

# Status Colors
ring-ver-color=ef9f76
inside-ver-color=303446
ring-wrong-color=f38ba8
inside-wrong-color=303446
ring-clear-color=a6e3a1
inside-clear-color=303446
