# Catppuccin Latte Peach Optimized Swaylock Config
color=eff1f5
indicator-radius=100
indicator-thickness=12
ring-color=fe640b
key-hl-color=acb0be
bs-hl-color=f38ba8
text-color=4c4f69
line-color=00000000
inside-color=eff1f5
separator-color=00000000

# Status Colors
ring-ver-color=fe640b
inside-ver-color=eff1f5
ring-wrong-color=f38ba8
inside-wrong-color=eff1f5
ring-clear-color=a6e3a1
inside-clear-color=eff1f5
