# ~/.config/swaylock/themes/dracula.conf
color=282a36
indicator-radius=100
indicator-thickness=12
ring-color=44475a
key-hl-color=bd93f9
bs-hl-color=ff5555
text-color=f8f8f2
line-color=00000000
inside-color=282a36
separator-color=00000000

# Status Colors
ring-ver-color=bd93f9
inside-ver-color=282a36
ring-wrong-color=ff5555
inside-wrong-color=282a36
ring-clear-color=50fa7b
inside-clear-color=282a36
