###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$file_manager = thunar
$menu = wofi
$web_browser = firefox
$password_manager = wofi-pass

$left=h
$down=j
$up=k
$right=l
