LogLevel 3
LogDir "default"
DefaultRate 0
DefaultPitch 0
DefaultVolume 100
DefaultLanguage "en"
AudioOutputMethod "pulse"

AddModule "lessac" "sd_generic" "piper-lessac.conf"
AddModule "cori" "sd_generic" "piper-cori.conf"
AddModule "alan" "sd_generic" "piper-alan.conf"
AddModule "jenny" "sd_generic" "piper-jenny.conf"
AddModule "ryan" "sd_generic" "piper-ryan.conf"
AddModule "alba" "sd_generic" "piper-alba.conf"
AddModule "amy" "sd_generic" "piper-amy.conf"

DefaultModule alan

Include "clients/*.conf"
