# Arc Dark
# Based on Arc-Dark GTK theme palette

set $base       #2f343f
set $mantle     #262b33
set $text       #d3dae3
set $overlay0   #404552
set $red        #cf6a4c
set $accent     #5294e2

# Property Name         Border      Background  Text    Indicator   Child Border
client.focused          $accent     $accent     $text   $accent     $accent
client.focused_inactive $overlay0   $base       $text   $overlay0   $overlay0
client.unfocused        $overlay0   $base       $text   $overlay0   $overlay0
client.urgent           $red        $base       $red    $overlay0   $red
client.placeholder      $overlay0   $base       $text   $overlay0   $overlay0
client.background       $base
